# Generated by Django 2.2.6 on 2021-09-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210909_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='к какой группе относится', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Group', verbose_name='группа'),
        ),
    ]
